# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Toward Ten Thousand Hours
tagline:             'The programning blog of Nick Tobey'
description:         ''
url:                 http://nicktobey.me/
baseurl:             http://nicktobey.me/
repo:                nicktobey/nicktobey.github.io
paginate:            5

# About/contact
author:
  name:              Nick Tobey
  url:               http://nicktobey.me/
  email:             nicktobey@nicktobey.me

# Custom vars
version:             1.0.0
